general {
    lock_cmd = pidof hyprlock || hyprlock
    # ignore_dbus_inhibit = false             # Ignore dbus idle-inhibit requests (false = respect them)
    # ignore_systemd_inhibit = false          # Ignore systemd-inhibit --what=idle (false = respect them)
  }

listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10 # Save and set brightness to 1%
    on-resume = brightnessctl -r # Restore brightness on activity
}

listener {
    timeout = 600
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                            # screen off when timeout has passed
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && brightnessctl -r          # screen on when activity is detected after timeout has fired.
}

listener {
    timeout = 1200
    on-timeout = loginctl lock-session # Try system lock, fallback to $LOCKSCREEN
}


listener {
    timeout = 1800
    on-timeout = systemctl suspend # Suspend system
}
